# Generated by Django 5.1.7 on 2025-05-18 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('publicprofile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicService',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('service_type', models.CharField(choices=[('offer', 'Offer'), ('search', 'Search'), ('na', 'Not Available')], default='na', max_length=6)),
                ('additional_location_info', models.CharField(blank=True, max_length=350, null=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='public_services', to='core.category')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='public_services', to='core.location')),
                ('public_profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_services', to='publicprofile.publicprofile')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='public_services', to='core.region')),
                ('sub_categories', models.ManyToManyField(related_name='public_services', to='core.subcategory')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
