# Generated by Django 5.1.7 on 2025-05-23 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicservice', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicservice',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
