# Generated by Django 5.1.7 on 2025-04-06 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicservices', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicservice',
            old_name='user_id',
            new_name='user',
        ),
    ]
