# Generated by Django 5.1.7 on 2025-04-07 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicservices', '0002_rename_user_id_publicservice_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicservice',
            name='service_type',
            field=models.CharField(choices=[('offer', 'Offer'), ('search', 'Search'), ('na', 'Not Available')], default='na', max_length=6),
        ),
    ]
