# Generated by Django 5.1.7 on 2025-04-14 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('publicservices', '0003_publicservice_service_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicservice',
            name='categories',
        ),
        migrations.AddField(
            model_name='publicservice',
            name='additional_location_info',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
        migrations.AddField(
            model_name='publicservice',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='public_services', to='core.category'),
        ),
    ]
