# Generated by Django 5.1.7 on 2025-06-16 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registereduser',
            old_name='place',
            new_name='location',
        ),
    ]
