# Generated by Django 5.1.7 on 2025-06-16 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_category_keywords_remove_subcategory_keywords'),
        ('usermanagment', '0002_rename_place_registereduser_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registereduser',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_users', to='core.region'),
        ),
    ]
