# Generated by Django 5.1.7 on 2025-03-16 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PublicProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_profile_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=250, null=True)),
                ('description', models.TextField(null=True)),
                ('contact_info', models.TextField(null=True)),
                ('public_profile_picture', models.ImageField(null=True, upload_to='public_profile_pictures/')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
