# Generated by Django 5.1.7 on 2025-04-12 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicprofile', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicprofile',
            old_name='username',
            new_name='showed_name',
        ),
        migrations.AlterField(
            model_name='publicprofile',
            name='contact_info',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='publicprofile',
            name='description',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
