# Generated by Django 5.1.7 on 2025-05-24 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicprofile', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicprofile',
            name='description',
            field=models.TextField(max_length=3000, null=True),
        ),
    ]
