# Generated by Django 5.1.7 on 2025-03-22 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registereduser',
            old_name='country',
            new_name='place',
        ),
        migrations.RemoveField(
            model_name='registereduser',
            name='gender',
        ),
        migrations.AddField(
            model_name='registereduser',
            name='region',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
    ]
