# Generated by Django 5.1.7 on 2025-03-22 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagment', '0002_rename_country_registereduser_place_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registereduser',
            name='city',
        ),
    ]
