# Generated by Django 5.1.7 on 2025-04-07 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagment', '0003_remove_registereduser_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registereduser',
            name='profile_picture',
        ),
    ]
