# Generated by Django 5.1.7 on 2025-06-16 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='keywords',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='keywords',
        ),
    ]
