version: "3.8"

services:
  django:
    build: ./Backend
    container_name: django
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    volumes:
      - ./Backend/:/srv/app
      - static:/srv/app/static
      - media:/srv/app/media
    depends_on:
      - db
  react:
    build: ./Frontend
    container_name: react
    command: npm run dev
    ports:
      - 5173:5173
    env_file:
      - ./.env.dev
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./Frontend/:/srv/app
      - node_modules:/srv/app/node_modules
    depends_on:
      - django
  db:
    image: postgres:16.1-alpine
    container_name: db
    ports:
      - 5432:5432
    env_file: ./.env.dev
    volumes:
      - postgres_data:/var/lib/postgresql/data
  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - 8080:80
    restart: always
    volumes:
      - static:/srv/app/static
      - media:/srv/app/media
    depends_on:
      - django
      - react
      - db

volumes:
  node_modules:
  postgres_data:
  media:
  static:
