# Generated by Django 5.1.7 on 2025-05-24 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('page_visit', models.IntegerField(default=1)),
            ],
        ),
    ]
