const regionsConfiguration = [
  { name: 'Aargau' },
  { name: 'Appenzell Ausserrhoden' },
  { name: 'Appenzell Innerrhoden' },
  { name: 'Basel-Landschaft' },
  { name: 'Basel-Stadt' },
  { name: 'Bern' },
  { name: 'Freiburg' },
  { name: 'Genf' },
  { name: 'Glarus' },
  { name: 'Graubünden' },
  { name: 'Jura' },
  { name: 'Luzern' },
  { name: 'Neuenburg' },
  { name: 'Nidwalden' },
  { name: 'Obwalden' },
  { name: 'Schaffhausen' },
  { name: 'Schwyz' },
  { name: 'Solothurn' },
  { name: 'St. Gallen' },
  { name: 'Tessin' },
  { name: 'Thurgau' },
  { name: 'Uri' },
  { name: 'Waadt' },
  { name: 'Wallis' },
  { name: 'Zug' },
  { name: 'Zürich' },
];
export default regionsConfiguration;
