# Generated by Django 5.1.7 on 2025-06-13 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyticsdataentry',
            name='page_visit',
            field=models.BooleanField(default=True),
        ),
    ]
